#!/usr/bin/env bash
# Check if the fourth argument is empty
if [[ -z "$4" ]]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Construct the server host address
host="$3@$2:~/"

# Transfer the file using scp
scp -o StrictHostKeyChecking=no -i "$4" "$1" "$host"
